// Frontend/src/components/formColors.vue
<script setup>
import { ref, defineProps } from 'vue';
import { useRouter } from 'vue-router';
const primaryColor = ref('');
const secondaryColor = ref('');
const ternaryColor = ref('');
const cuarternaryColor = ref('');
const neutralColor = ref('');
const invalidData = ref(false);

const props = defineProps({
    onRefreshListColors: {
        type: Function,
        required: true
    },
    onRefreshColorsPreview: {
        type: Function,
        required: true
    }
});

const onSaveColors = async (event) => {
    event.preventDefault();
    if (!primaryColor.value || !secondaryColor.value || !ternaryColor.value || !cuarternaryColor.value || !neutralColor.value) {
        invalidData.value = true;
        return;
    }
    const colors = {
        primary_color: primaryColor.value.slice(1),
        secondary_color: secondaryColor.value.slice(1),
        ternary_color: ternaryColor.value.slice(1),
        cuarternary_color: cuarternaryColor.value.slice(1),
        neutral_color: neutralColor.value.slice(1),
        is_selected: false
    };
    try {
        const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/Colors/1`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(colors)
        });
        if (response.ok) {
            props.onRefreshListColors();
            primaryColor.value = '';
            secondaryColor.value = '';
            ternaryColor.value = '';
            cuarternaryColor.value = '';
            neutralColor.value = '';
            const colors = {
                primary_color: '',
                secondary_color: '',
                ternary_color: '',
                cuarternary_color: '',
                neutral_color: ''
            };
            props.onRefreshColorsPreview(colors);
        }
    } catch (error) {
        console.error('Error al guardar los colores:', error);
    }
};

const onInputColor = (event) => {
    const input = event.target;
    invalidData.value = false;
    const colors = {
        primary_color: primaryColor.value.slice(1),
        secondary_color: secondaryColor.value.slice(1),
        ternary_color: ternaryColor.value.slice(1),
        cuarternary_color: cuarternaryColor.value.slice(1),
        neutral_color: neutralColor.value.slice(1)
    };
    props.onRefreshColorsPreview(colors);

};

const onEditColors = async (event) => {
    event.preventDefault();
    if (!primaryColor.value || !secondaryColor.value || !ternaryColor.value || !cuarternaryColor.value || !neutralColor.value) {
        invalidData.value = true;
        return;
    }
    try {
        const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/Colors`);
        if (!response.ok) throw new Error(`Error de API: ${response.status}`);
        const listColors = await response.json();
        const selectedColor = listColors.find((color) => color.is_selected === 1);
        const otherResponse = await fetch(`${import.meta.env.VITE_BACKEND_URL}/Colors/${selectedColor.id_colors}`, {
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                primary_color: primaryColor.value.slice(1),
                secondary_color: secondaryColor.value.slice(1),
                ternary_color: ternaryColor.value.slice(1),
                cuarternary_color: cuarternaryColor.value.slice(1),
                neutral_color: neutralColor.value.slice(1),
                is_selected: true
            })
        });
        if (!otherResponse.ok) throw new Error(`Error de API: ${otherResponse.status}`);
        props.onRefreshListColors();
        primaryColor.value = '';
        secondaryColor.value = '';
        ternaryColor.value = '';
        cuarternaryColor.value = '';
        neutralColor.value = '';
        const colors = {
            primary_color: '',
            secondary_color: '',
            ternary_color: '',
            cuarternary_color: '',
            neutral_color: ''
        };
        props.onRefreshColorsPreview(colors);
    } catch (error) {
        console.error('Error al editar los colores:', error);
    }
}
</script>

<template>
    <form class="w-full h-152 flex flex-col items-center gap-5 px-2 py-3">
        <div class=" w-full h-22 flex flex-col gap-1">
            <label class="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" for="primary_color">Color
                Primario</label>
            <input class="w-full h-full" v-model="primaryColor" @input="onInputColor" type="color"
                placeholder="Ingrese el color primario de la platilla" name="primary_color" id="primary_color"
                required />
        </div>
        <div class=" w-full h-22 flex flex-col gap-1">
            <label class="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" for="secondary_color">Color
                Secundario</label>
            <input class="w-full h-full" v-model="secondaryColor" @input="onInputColor" type="color"
                name="secondary_color" id="secondary_color" required />
        </div>
        <div class=" w-full h-22 flex flex-col gap-1">
            <label class="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700">Color Terciario</label>
            <input class="w-full h-full" v-model="ternaryColor" @input="onInputColor" type="color" name="ternary_color"
                id="ternary_color" required />
        </div>
        <div class=" w-full h-22 flex flex-col gap-1">
            <label class="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700">Color cuaternario</label>
            <input class="w-full h-full" v-model="cuarternaryColor" @input="onInputColor" type="color"
                name="cuarternary_color" id="cuarternary_color" required />
        </div>
        <div class=" w-full h-22 flex flex-col gap-1">
            <label class="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700">Color neutral</label>
            <input class="w-full h-full" v-model="neutralColor" @input="onInputColor" type="color" name="neutral_color"
                id="neutral_color" required />
        </div>
        <span v-if="invalidData" class="text-red-600">Complete todos los campos.</span>
        <div class="w-full flex justify-between">
            <button type="submit"
                class="bg-[#F97316] text-white px-3 py-2 rounded-md font-medium hover:bg-[#F97316]/75 transition-colors cursor-pointer w-1/3"
                @click="onSaveColors">
                Crear
            </button>
            <button type="submit"
                class="bg-[#F97316] text-white px-3 py-2 rounded-md font-medium hover:bg-[#F97316]/75 transition-colors cursor-pointer w-1/3"
                @click="onEditColors">
                Editar
            </button>
        </div>
    </form>
</template>

// saveedra-react/Plantilla en React/src/components/formColors.tsx
import React, { useState } from "react";
import { axiosInstance } from "../context/axiosInstances";


const FormColors = ({onRefreshListColors, onRefreshColorsPreview}) => {
    const [primaryColorInput, setPrimaryColorInput] = useState("");
    const [secondaryColorInput, setSecondaryColorInput] = useState("");
    const [ternaryColorInput, setTernaryColorInput] = useState("");
    const [cuarternaryColorInput, setCuarternaryColorInput] = useState("");
    const [neutralColorInput, setNeutralColorInput] = useState("");
    const [invalidData, setInvalidData] = useState(false);
    
    const onSaveColors = async(event: React.FormEvent) => {
        event.preventDefault();
        if (primaryColorInput === "" || secondaryColorInput === "" || ternaryColorInput === "" || cuarternaryColorInput === "" || neutralColorInput === "") {
            setInvalidData(true);
            return;
        }

        const colors = {
            primary_color: primaryColorInput.slice(1),
            secondary_color: secondaryColorInput.slice(1),
            ternary_color: ternaryColorInput.slice(1),
            cuarternary_color: cuarternaryColorInput.slice(1),
            neutral_color: neutralColorInput.slice(1),
            is_selected: false
        };
        try {
            const response = await axiosInstance.post('/Colors', colors);
            
                onRefreshListColors();
                setPrimaryColorInput("");
                setSecondaryColorInput("");
                setTernaryColorInput("");
                setCuarternaryColorInput("");
                setNeutralColorInput("");
                const newColors = {
                    primary_color: "",
                    secondary_color: "",
                    ternary_color: "",
                    cuarternary_color: "",
                    neutral_color: ""
                };
                onRefreshColorsPreview(newColors);
            
        } catch (error) {
            console.error("Error al guardar los colores:", error);
        }
    };
    const onInputColor = (event) => {
        const input = event.target;
        setInvalidData(false);
        const colors = {
            primary_color: primaryColorInput.slice(1),
            secondary_color: secondaryColorInput.slice(1),
            ternary_color: ternaryColorInput.slice(1),
            cuarternary_color: cuarternaryColorInput.slice(1),
            neutral_color: neutralColorInput.slice(1)
        };
        onRefreshColorsPreview(colors);
    };

    const onEditColors = async (event: React.FormEvent) => {
        event.preventDefault();
        if (primaryColorInput === "" || secondaryColorInput === "" || ternaryColorInput === "" || cuarternaryColorInput === "" || neutralColorInput === "") {
            setInvalidData(true);
            return;
        }

        try {
            const reponse = await axiosInstance.get('/Colors/selected');
            const selectedColor = reponse.data.data;
            const colors = {
                primary_color: primaryColorInput.slice(1),
                secondary_color: secondaryColorInput.slice(1),
                ternary_color: ternaryColorInput.slice(1),
                cuarternary_color: cuarternaryColorInput.slice(1),
                neutral_color: neutralColorInput.slice(1),
                is_selected: true
            };
            const otherResponse = await axiosInstance.patch(`/Colors/${selectedColor.id_colors}`, colors);
            onRefreshListColors();
            setPrimaryColorInput("");
            setSecondaryColorInput("");
            setTernaryColorInput("");
            setCuarternaryColorInput("");
            setNeutralColorInput("");
            const newColors = {
                primary_color: "",
                secondary_color: "",
                ternary_color: "",
                cuarternary_color: "",
                neutral_color: ""
            };
            onRefreshColorsPreview(newColors);
        } catch (error) {
            console.error("Error al editar los colores:", error);
        }
    };
    return (
        <form className="w-full h-full  flex flex-col items-center gap-5 px-2 py-3">
            <div className="w-full h-24 flex flex-col gap-1">
                <label className="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" htmlFor="primary_color">
                    Color Primario
                </label>
                <input
                    className="w-full h-full"
                    type="color"
                    name="primary_color"
                    id="primary_color"
                    value={primaryColorInput}
                    onChange={(e) => {
                        setPrimaryColorInput(e.target.value);
                        onInputColor(e);
                    }}
                    required
                />
            </div>
            <div className="w-full h-24 flex flex-col gap-1">
                <label className="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" htmlFor="secondary_color">
                    Color Secundario
                </label>
                <input
                    className="w-full h-full"
                    type="color"
                    name="secondary_color"
                    id="secondary_color"
                    value={secondaryColorInput}
                    onChange={(e) => {
                        setSecondaryColorInput(e.target.value);
                        onInputColor(e);
                    }}
                    required
                />
            </div>
            <div className="w-full h-24 flex flex-col gap-1">
                <label className="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700">
                    Color Terciario
                </label>
                <input
                    className="w-full h-full"
                    type="color"
                    name="ternary_color"
                    id="ternary_color"
                    value={ternaryColorInput}
                    onChange={(e) => {
                        setTernaryColorInput(e.target.value);
                        onInputColor(e);
                    }}
                    required
                />
            </div>
            <div className="w-full h-24 flex flex-col gap-1">
                <label className="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" htmlFor="cuarternary_color">
                    Color cuaternario
                </label>
                <input
                    className="w-full h-full"
                    type="color"
                    name="cuarternary_color"
                    id="cuarternary_color"
                    value={cuarternaryColorInput}
                    onChange={(e) => {
                        setCuarternaryColorInput(e.target.value);
                        onInputColor(e);
                    }}
                    required
                />
            </div>
            <div className="w-full h-24 flex flex-col gap-1">
                <label className="text-lg trancking-wide font-500 w-full border-b-2 border-gray-700" htmlFor="neutral_color">
                    Color neutral
                </label>
                <input
                    className="w-full h-full"
                    type="color"
                    name="neutral_color"
                    id="neutral_color"
                    value={neutralColorInput}
                    onChange={(e) => {
                        setNeutralColorInput(e.target.value);
                        onInputColor(e);
                    }}
                    required
                />
            </div>
            { invalidData && (
                <span className="text-red-600">
                    Complete todos los campos.
                </span>
            )}
            <div className="w-full flex justify-between">
                <button type="submit" className="bg-[#F97316] text-white px-3 py-2 rounded-md font-medium hover:bg-[#F97316]/75 transition-colors cursor-pointer w-1/3" onClick={onSaveColors}>Crear</button>
                <button type="submit" className="bg-[#F97316] text-white px-3 py-2 rounded-md font-medium hover:bg-[#F97316]/75 transition-colors cursor-pointer w-1/3" onClick={onEditColors}>Editar</button>
            </div>
        </form>
    )
}

export default FormColors;
