// Plantilla en React/src/components/CardFonts.tsx

const CardFonts = (primaryFont: string, secondaryFont: string, textTitle: string, textSubtitle: string, textParagraph: string) => {
    return (
        <div className="w-full h-full border-2 border-black flex flex-col items-center justify-center p-5 my-2 rounded-lg overflow-auto">
            <div className="text-center">
                <h1 className="text-md md:text-5xl font-bold mb-4" style={{fontFamily: `${secondaryFont}`, fontSize: `${textTitle}px`}}>Tu Bienestar es Nuestra Prioridad</h1>
                <p className="text-sm sm:text-2xl max-w-3xl mx-auto" style={{fontFamily: `${primaryFont}`, fontSize: `${textSubtitle}px`}}>Servicios de salud integral para toda la familia</p>
                <button className="mt-8 bg-[#F97316] text-white font-medium py-3 px-6 rounded-md transition-colors" style={{fontFamily: `${primaryFont}`, fontSize: `${textParagraph}px`}}>Agendar Cita</button>
            </div>
        </div>
    )
}

export default CardFonts;

// Frontend/src/components/CardFonts.vue
<script setup>
import { computed } from 'vue';


const props = defineProps({
    fonts: {
        type: Object,
        required: true
    }
});

const primaryFont = computed(() => {
    return props.fonts.primaryFont || 'RobotoSans';
})

const secondaryFont = computed(() => {
    return props.fonts.secondaryFont || 'RobotoSerif';
})

const textTitle = computed(() => {
    return props.fonts.textTitle || '36';
})

const textSubtitle = computed(() => {
    return props.fonts.textSubtitle || '24';
})

const textParagraph = computed(() => {
    return props.fonts.textParagraph || '16';
})

</script>

<template>
    <div class="w-full h-full border-2 border-black flex flex-col items-center justify-center p-5 my-2 rounded-lg overflow-auto">
        <div class="text-center ">
            <h1 class="text-md md:text-5xl font-bold mb-4" :style="`font-family: ${secondaryFont}; font-size: ${textTitle}px;`">Tu Bienestar es Nuestra Prioridad</h1>
            <p class="text-sm sm:text-2xl max-w-3xl mx-auto" :style="`font-family: ${primaryFont}; font-size: ${textSubtitle}px;`">Servicios de salud integral para toda la familia</p>
            <button class="mt-8 bg-[#F97316] text-white font-medium py-3 px-6 rounded-md transition-colors" :style="`font-family: ${primaryFont}; font-size: ${textParagraph}px;`">
                Agendar Cita
            </button>
        </div>
    </div>
</template>
