// saveedra-react/Plantilla en React/src/components/Admin/Header.tsx
import React from "react";

const Header = () => {
    return (
        <header className="bg-blue-600 w-full h-16 flex items-center">
            <article className="text-white text-lg tracking-wide font-bold flex items-center justify-between w-full px-5">
                <h1>Bienvenido a la parte administrativa</h1>
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 24 24" fill="none" stroke="#eee" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-chart-no-axes-gantt-icon lucide-chart-no-axes-gantt">
                    <path d="M8 6h10"/><path d="M6 12h9"/><path d="M11 18h7"/>
                </svg>
            </article>
        </header>
    )
}

export default Header;

// Vue/Frontend/src/components/Admin/Header.vue
<template>
    <header class="bg-blue-600 w-full h-16 flex items-center">
        <article class="text-white text-lg tracking-wide font-bold flex items-center justify-between w-full px-5">
            <h1>Bienvenido a la parte administrativa</h1>
            <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 24 24" fill="none" stroke="#eee" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chart-no-axes-gantt-icon lucide-chart-no-axes-gantt">
                <path d="M8 6h10"/><path d="M6 12h9"/><path d="M11 18h7"/>
            </svg>
        </article>
    </header>
</template>
