// Vue/Frontend/src/components/Admin/SectionsVideo.vue
<script setup>
import { ref } from 'vue';
import FormVideos from '@/components/FormVideos.vue';
import ListVideos from '@/components/ListVideos.vue';

const modoCrear = ref(true);
const videoEdit = ref(null);
const previewData = ref({
  videoUrl: null,
  primarySubtitleUrl: null,
  secondarySubtitleUrl: null,
  primaryAudioUrl: null,
  secondaryAudioUrl: null,
  videoMetadata: null,
});

const handleEditClick = (video) => {
  modoCrear.value = false;
  videoEdit.value = {
    id: video.id_video,
    url_video: video.url_video,
    url_primary_subtitle: video.url_primary_subtitle,
    url_secondary_subtitle: video.url_secondary_subtitle,
    url_primary_audio: video.url_primary_audio,
    url_secondary_audio: video.url_secondary_audio,
    file_name: video.name_video,
    file_format: video.format_video,
    duration: String(video.duration_video),
    size: String(video.size_video),
  };
};

const handleSuccess = () => {
  // Volver al modo crear tras crear/actualizar
  modoCrear.value = true;
  videoEdit.value = null;
};

const handlePreviewChange = (data) => {
  previewData.value = data;
};
</script>

<template>
  <section class="p-4">
    <h2 class="text-xl font-semibold mb-4 text-center">Administrar Videos</h2>
    <div class="flex flex-col lg:flex-row gap-6">
      <FormVideos
        :modoCrear="modoCrear"
        :videoEdit="videoEdit"
        @success="handleSuccess"
        @previewChange="handlePreviewChange"
      />
      <ListVideos @edit="handleEditClick" />
    </div>

    <!-- Vista previa simple -->
    <div v-if="previewData.videoUrl" class="mt-6">
      <h3 class="text-lg font-semibold mb-2">Previsualización</h3>
      <video :src="previewData.videoUrl" controls class="max-w-full rounded" />
    </div>
  </section>
</template>

// React/Plantilla en React/src/components/Admin/SectionsVideo.tsx
import { useState, useEffect } from "react";
import { CardVideos } from "../CardVideos";
import { FormVideos } from "../FormVideos";
import { ListVideos } from "../ListVideos";
import { axiosInstance } from "../../context/axiosInstances";
import { PreviewData, VideoType } from "../../types/video";

export const SectionsVideo = () => {
  const [videos, setVideos] = useState<VideoType[]>([]);
  const [videoEdit, setVideoEdit] = useState<VideoType | null>(null);
  const [modoCrear, setModoCrear] = useState(true);

  const [videoPreview, setVideoPreview] = useState<PreviewData>({
    videoUrl: null,
    primarySubtitleUrl: null,
    secondarySubtitleUrl: null,
    primaryAudioUrl: null,
    secondaryAudioUrl: null,
    videoMetadata: null,
  });

  const loadVideos = async () => {
    try {
      const res = await axiosInstance.get("/videos");
      setVideos(res.data.data || res.data);
    } catch (error) {
      console.error("Error cargando videos:", error);
    }
  };

  useEffect(() => {
    loadVideos();
  }, []);

  const handleEditVideo = (video: VideoType) => {
    setVideoEdit(video);
    setModoCrear(false);
    const newPreviewData: PreviewData = {
      videoUrl: video.url_video,
      primarySubtitleUrl: video.url_primary_subtitle,
      secondarySubtitleUrl: video.url_secondary_subtitle,
      primaryAudioUrl: video.url_primary_audio,
      secondaryAudioUrl: video.url_secondary_audio,
      videoMetadata: {
        fileName: video.file_name,
        fileFormat: video.file_format,
        duration: video.duration,
        size: video.size,
      },
    };
    setVideoPreview(newPreviewData);
  };

  const handleFormSuccess = () => {
    setModoCrear(true);
    setVideoEdit(null);
    const cleanPreviewData = {
      videoUrl: null,
      primarySubtitleUrl: null,
      secondarySubtitleUrl: null,
      primaryAudioUrl: null,
      secondaryAudioUrl: null,
      videoMetadata: null,
    };
    setVideoPreview(cleanPreviewData);
    loadVideos();
  };

  const handlePreviewChange = (previewData: PreviewData) => {
    setVideoPreview(previewData);
  };

  return (
    <div className="flex flex-wrap flex-1 gap-6 p-4">
      <FormVideos
        modoCrear={modoCrear}
        videoEdit={videoEdit}
        onSuccess={handleFormSuccess}
        onPreviewChange={handlePreviewChange}
      />
      <CardVideos
        previewData={videoPreview}
      />
      <ListVideos
        videos={videos}
        onEditClick={handleEditVideo}
      />
    </div>
  );
};
