// Plantilla en React/src/components/MapSelector.tsx
import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import 'leaflet-control-geocoder/dist/Control.Geocoder.css';
import { LocationData } from '../types/user';

// Configurar iconos por defecto
let DefaultIcon = L.icon({
  iconUrl: "https://unpkg.com/leaflet@1.9.3/dist/images/marker-icon.png",
  shadowUrl: "https://unpkg.com/leaflet@1.9.3/dist/images/marker-shadow.png",
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41]
});

L.Marker.prototype.options.icon = DefaultIcon;

interface MapSelectorProps {
  onLocationSelect: (location: LocationData) => void;
  initialLat?: number;
  initialLng?: number;
  height?: string;
}

const MapSelector: React.FC<MapSelectorProps> = ({ 
  onLocationSelect, 
  initialLat = 51.505, 
  initialLng = -0.09,
  height = "400px"
}) => {
  const mapRef = useRef<HTMLDivElement>(null);
  const mapInstanceRef = useRef<L.Map | null>(null);
  const [locationInfo, setLocationInfo] = useState<string>('Selecciona una ubicación en el mapa');

  useEffect(() => {
    if (!mapRef.current || mapInstanceRef.current) return;

    // Importar el geocoder dinámicamente
    const loadGeocoder = async () => {
      try {
        const { geocoder } = await import('leaflet-control-geocoder');
        
        // Inicializar el mapa
        const map = L.map(mapRef.current!).setView([initialLat, initialLng], 13);
        mapInstanceRef.current = map;

        // Añadir capa de OpenStreetMap
        L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
          attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        // Añadir buscador al mapa usando el plugin de geocoder
        const geocoderControl = geocoder({
          defaultMarkGeocode: false,
        })
          .on("markgeocode", function (e: any) {
            const bbox = e.geocode.bbox;
            const poly = L.polygon([
              bbox.getSouthEast(),
              bbox.getNorthEast(),
              bbox.getNorthWest(),
              bbox.getSouthWest(),
            ]).addTo(map);
            map.fitBounds(poly.getBounds());

            // Mostrar información de la ubicación
            const { name, properties } = e.geocode;
            const city = properties.city || "-";
            const state = properties.state || "-";
            const country = properties.country || "-";
            const address = name || "-";
            
            setLocationInfo(`Ciudad: ${city}, Estado: ${state}, País: ${country}`);
            
            // Obtener coordenadas del centro del polígono
            const center = poly.getBounds().getCenter();
            const locationData: LocationData = {
              lat: center.lat,
              lng: center.lng,
              address,
              city,
              state,
              country,
              postalCode: properties.postcode || ""
            };
            onLocationSelect(locationData);
          })
          .addTo(map);

        // Manejar clics en el mapa
        map.on("click", async function (e) {
          const lat = e.latlng.lat;
          const lng = e.latlng.lng;

          // Usar Nominatim para obtener información de la ubicación
          try {
            const response = await fetch(
              `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`
            );
            const data = await response.json();
            
            const address = data.display_name || "Desconocida";
            const city = data.address.city || data.address.town || data.address.village || "Desconocida";
            const state = data.address.state || "Desconocido";
            const country = data.address.country || "Desconocido";
            const postalCode = data.address.postcode || "";

            setLocationInfo(`Latitud: ${lat.toFixed(6)}, Longitud: ${lng.toFixed(6)}\nCiudad: ${city}, País: ${country}`);
            
            const locationData: LocationData = {
              lat,
              lng,
              address,
              city,
              state,
              country,
              postalCode
            };
            onLocationSelect(locationData);
          } catch (error) {
            console.error("Error al obtener datos de geocodificación:", error);
            setLocationInfo(`Latitud: ${lat.toFixed(6)}, Longitud: ${lng.toFixed(6)}`);
            
            const locationData: LocationData = {
              lat,
              lng,
              address: "Ubicación seleccionada",
              city: "Desconocida",
              state: "Desconocido",
              country: "Desconocido",
              postalCode: ""
            };
            onLocationSelect(locationData);
          }
        });

      } catch (error) {
        console.error('Error al cargar el geocoder:', error);
        
        // Fallback: crear mapa sin geocoder
        const map = L.map(mapRef.current!).setView([initialLat, initialLng], 13);
        mapInstanceRef.current = map;

        L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
          attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        // Solo manejar clics en el mapa
        map.on("click", async function (e) {
          const lat = e.latlng.lat;
          const lng = e.latlng.lng;

          try {
            const response = await fetch(
              `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`
            );
            const data = await response.json();
            
            const address = data.display_name || "Desconocida";
            const city = data.address.city || data.address.town || data.address.village || "Desconocida";
            const state = data.address.state || "Desconocido";
            const country = data.address.country || "Desconocido";
            const postalCode = data.address.postcode || "";

            setLocationInfo(`Latitud: ${lat.toFixed(6)}, Longitud: ${lng.toFixed(6)}\nCiudad: ${city}, País: ${country}`);
            
            const locationData: LocationData = {
              lat,
              lng,
              address,
              city,
              state,
              country,
              postalCode
            };
            onLocationSelect(locationData);
          } catch (error) {
            console.error("Error al obtener datos de geocodificación:", error);
            setLocationInfo(`Latitud: ${lat.toFixed(6)}, Longitud: ${lng.toFixed(6)}`);
            
            const locationData: LocationData = {
              lat,
              lng,
              address: "Ubicación seleccionada",
              city: "Desconocida",
              state: "Desconocido",
              country: "Desconocido",
              postalCode: ""
            };
            onLocationSelect(locationData);
          }
        });
      }
    };

    loadGeocoder();

    return () => {
      if (mapInstanceRef.current) {
        mapInstanceRef.current.remove();
        mapInstanceRef.current = null;
      }
    };
  }, [initialLat, initialLng, onLocationSelect]);

  return (
    <div className="w-full">
      <div 
        ref={mapRef} 
        style={{ height }} 
        className="w-full rounded-lg border border-gray-300"
      />
      <div className="mt-2 p-2 bg-gray-50 rounded text-sm text-gray-700">
        {locationInfo}
      </div>
    </div>
  );
};

export default MapSelector;

// Vue/Frontend/src/components/MapSelector.vue
<script setup>
import { onMounted, onBeforeUnmount, ref } from 'vue';
import L from 'leaflet';

// Propiedades
const props = defineProps({
  initialLat: { type: Number, default: 51.505 },
  initialLng: { type: Number, default: -0.09 },
  height: { type: String, default: '400px' },
});

const emit = defineEmits(['locationSelect']);

const mapEl = ref(null);
let mapInstance = null;

// Resolver iconos por defecto de Leaflet en bundlers
const iconUrl = new URL('leaflet/dist/images/marker-icon.png', import.meta.url).toString();
const shadowUrl = new URL('leaflet/dist/images/marker-shadow.png', import.meta.url).toString();
const defaultIcon = L.icon({
  iconUrl,
  shadowUrl,
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41],
});
L.Marker.prototype.options.icon = defaultIcon;

onMounted(async () => {
  if (mapInstance) return;
  mapInstance = L.map(mapEl.value).setView([props.initialLat, props.initialLng], 13);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors',
  }).addTo(mapInstance);

  try {
    const module = await import('leaflet-control-geocoder');
    const geocoder = module.geocoder({ defaultMarkGeocode: false })
      .on('markgeocode', function (e) {
        const bbox = e.geocode.bbox;
        const poly = L.polygon([
          bbox.getSouthEast(),
          bbox.getNorthEast(),
          bbox.getNorthWest(),
          bbox.getSouthWest(),
        ]).addTo(mapInstance);
        mapInstance.fitBounds(poly.getBounds());

        const { name, properties } = e.geocode;
        const city = properties.city || '-';
        const state = properties.state || '-';
        const country = properties.country || '-';
        const address = name || '-';
        const center = poly.getBounds().getCenter();
        emit('locationSelect', {
          lat: center.lat,
          lng: center.lng,
          address,
          city,
          state,
          country,
          postalCode: properties.postcode || '',
        });
      })
      .addTo(mapInstance);
  } catch (err) {
    // Si falla el geocoder, dejamos solo el mapa
    console.warn('Geocoder no disponible:', err);
  }

  mapInstance.on('click', async function (e) {
    const { lat, lng } = e.latlng;
    try {
      const response = await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`);
      const data = await response.json();
      const address = data.display_name || 'Desconocida';
      const city = data.address?.city || data.address?.town || data.address?.village || 'Desconocida';
      const state = data.address?.state || 'Desconocido';
      const country = data.address?.country || 'Desconocido';
      const postalCode = data.address?.postcode || '';
      emit('locationSelect', { lat, lng, address, city, state, country, postalCode });
    } catch (error) {
      console.error('Error al obtener datos de geocodificación:', error);
      emit('locationSelect', { lat, lng, address: 'Ubicación seleccionada', city: 'Desconocida', state: 'Desconocido', country: 'Desconocido', postalCode: '' });
    }
  });
});

onBeforeUnmount(() => {
  if (mapInstance) {
    mapInstance.remove();
    mapInstance = null;
  }
});
</script>

<template>
  <div>
    <div ref="mapEl" :style="{ height }" class="w-full rounded-lg border border-quinary/5"></div>
  </div>
</template>

<style>
@import 'leaflet/dist/leaflet.css';
@import 'leaflet-control-geocoder/dist/Control.Geocoder.css';
</style>
