// Plantilla en React/src/Pages/Home.tsx
import React from "react";
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Services from '../components/Services';
import Gallery from '../components/Gallery';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import LoginModal from '../components/LoginModal';

const Home = () =>{
    return (
        <div className="bg-primary">
            <Navbar />
            <LoginModal />
            <Hero />
            <Services />
            <Gallery />
            <Contact />
            <Footer />
        </div>
    )
}
export default Home;

// Frontend/src/views/Home.vue
<script setup>
import Banner from '@/components/Banner.vue';
import Services from '@/components/Services.vue';
import Carrusel from '@/components/Carrusel.vue';
import ContactForm from '@/components/ContactForm.vue';
import Navbar from '@/components/Navbar.vue';
import LoginModal from '@/components/LoginModal.vue';
import Footer from '@/components/Footer.vue';
</script>

<template>
    <Navbar />
    <LoginModal />
    <Banner />
    <Services />
    <Carrusel />
    <ContactForm />
    <Footer />
</template>
